PZ_03
k0c0u/PZ_CODING pull request #1
Opened 2021-11-10 17:12 UTC by k0c0u

2021-11-12 12:27 UTC, EugeneTel requested changes
Отличная работа. Но интерфейс не использован для оружия.
Надо доработать немного.

2021-11-12 12:27 UTC, EugeneTel commented on Source/PZ_CODING/Public/Weapon/BaseWeapon.h
> +	void Reload();	// должна вызываться на кнопку R и когда после выстрела у оружия нет патронов
Вижу, интерфейс IReloadableInterface создан но не используется. По заданию надо чтобы использовался для оружия.

2021-11-12 12:27 UTC, EugeneTel commented on Source/PZ_CODING/Private/Weapon/BaseWeapon.cpp
> +		CurrentAmmo--;
Согласно кодинг стандарту во всех подобных вариантах нужно использовать фигурные скобки.
Вот хороший пример визуально кажется что CurrentAmmo--; выполнится при выполнении условия (есть отступ даже!)

2021-11-12 22:56 UTC, k0c0u commented on Source/PZ_CODING/Private/Weapon/BaseWeapon.cpp
> +		CurrentAmmo--;
if (CurrentAmmo == 0) 
{
   return;
}
Вы имеете ввиду так необходимо делать запись кода?

2021-11-13 09:25 UTC, EugeneTel approved these changes
Отличная работа! Принято.

2021-11-13 09:25 UTC, EugeneTel commented on Source/PZ_CODING/Public/Weapon/BaseWeapon.h
> +	void Reload();
Нет необходимости объявлять Reload(). Достаточно перегрузить Reload_Implementation

2021-11-15 15:41 UTC, merged